env:                                   # The environment, mandatory
  contexts :                           # List of 1 or more contexts, mandatory
    - name: test-config                # Name to be used to refer to this context in other jobs, mandatory
      urls:
      # - "https://.*.example.com"
        - http://localhost:3000
      includePaths:
      # - "https://.*.example.com/.*"
        - http://localhost:3000/.*
      excludePaths: []
      authentication:
        method: "script"
        parameters:
          script: "<PATH_TO_YOUR_SCRIPT_IN_THE_SCB_ENVIRONMENT>/KeycloakClientCredentials.js"
          scriptEngine: "Oracle Nashorn"
          EndpointForAuthentication: "https://example.com/v1/token"
        verification:
          method: "response"
          loggedOutRegex: "(Unauthorized)|(token expired)"
          pollFrequency: 60
          pollUnits: "requests"
          pollUrl: ""
          pollPostData: ""
      sessionManagement:
        method: "cookie"
        parameters: {}
      users:
      - name: "internal-user"
        credentials:
          client_id: "user"
          client_secret: "pass"
  parameters:
    failOnError: true                  # If set exit on an error         
    failOnWarning: false               # If set exit on a warning
    progressToStdout: true             # If set will write job progress to stdout

jobs:
  - type: addOns                       # Add-on management
    install: [pscanrulesAlpha, pscanrulesBeta] # A list of non standard add-ons to install from the ZAP Marketplace
  - type: passiveScan-config           # Passive scan configuration
    parameters:
      maxAlertsPerRule: 10             # Int: Maximum number of alerts to raise per rule
      scanOnlyInScope: true            # Bool: Only scan URLs in scope (recommended)
  - type: spider                       # The traditional spider - fast but doesnt handle modern apps so well
    parameters:
      context: test-config             # String: Name of the context to spider, default: first context
      user: internal-user              # String: An optional user to use for authentication, must be defined in the env
      maxDuration: 2                   # Int: The max time in minutes the spider will be allowed to run for, default: 0 unlimited
  - type: spiderAjax                   # The ajax spider - slower than the spider but handles modern apps well
    parameters:
      context: test-config             # String: Name of the context to spider, default: first context
      maxDuration: 2                   # Int: The max time in minutes the ajax spider will be allowed to run for, default: 0 unlimited
  - type: passiveScan-wait             # Passive scan wait for the passive scanner to finish
    parameters:
      maxDuration: 10                  # Int: The max time to wait for the passive scanner, default: 0 unlimited
  - type: report                       # Report generation
    parameters:
      template: traditional-xml        # String: The template id, default : modern
      reportDir: /home/securecodebox/  # String: The directory into which the report will be written
      reportFile: zap-results          # String: The report file name pattern, default: {{yyyy-MM-dd}}-ZAP-Report-[[site]]
    risks:                             # List: The risks to include in this report, default all
      - high
      - medium
      - low