services:
  vault:
    image: vault:1.13.3
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_ADDR: 'http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./init.sh:/docker-entrypoint-initdev.d/init.sh
    network_mode: host
    # networks:
    #   - devnet

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev --import-realm --hostname-strict=false --hostname-url http://localhost:8080
    environment:
      # KEYCLOAK_FRONTEND_URL: http://keycloak:8080
      KEYCLOAK_FRONTEND_URL: http://localhost:8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - devnet
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json

  client:
    image: curlimages/curl:latest
    container_name: client
    networks:
      - devnet
    depends_on:
      - vault
      - keycloak
    entrypoint: ["sleep", "infinity"]

networks:
  devnet:
