env:
  contexts:
  - name: flypostContext
    urls:
    - http://localhost:3000/
    includePaths:
    - http://localhost:3000
    - http://localhost:3000/.*
    excludePaths:
    - .*\.js
    - .*\.css
    - .*\.png
    - .*\.jpeg
    authentication:
      method: script
      parameters:
        scriptEngine: "ECMAScript : Graal.js"
        script: /home/zap/.ZAP/scripts/authentication/general_auth.js
        scriptName: "general_auth"
        scriptType: "authentication"
        scriptDescription: "FlyPost Auth Script"
        authUrl: https://api.flypost.club/token
        # loginRequestBody: '{"login":"{%username%}","password":"{%password%}"}'
        # tokenPath: token
      verification:
        method: response
        loggedOutRegex: "(401|Unauthorized|expired|login)"
        pollFrequency: 30
        pollUnits: seconds
        pollUrl: https://api.flypost.club/manager/profile
    sessionManagement:
      method: cookie
    users:
    - name: flypost-user
      credentials:
        username: ${DAST_USERNAME}
        password: ${DAST_PASSWORD}
  parameters: {}

jobs:
- type: replacer
  rules:
    - description: Inject Bearer token
      matchType: req_header
      matchString: Authorization
      matchRegex: false
      replacementString: "Bearer {{logintoken}}"

- type: passiveScan-config
  parameters: {}

- type: spider
  parameters:
    context: flypostContext
    user: flypost-user
    url: http://localhost:3000/
    maxDuration: 10
    maxDepth: 10
    maxChildren: 20
    parseDsStore: true
  tests:
  - name: At least 100 URLs found
    type: stats
    onFail: INFO
    statistic: automation.spider.urls.added
    operator: '>='
    value: 100
  - name: No 401 responses
    type: stats
    onFail: WARN
    statistic: responses.401
    operator: '=='
    value: 0
  - name: No 403 responses
    type: stats
    onFail: WARN
    statistic: responses.403
    operator: '=='
    value: 0
  - name: Show found URLs
    type: stats
    onFail: WARN
    statistic: automation.spider.urls.added
    operator: '>='
    value: 200
  - name: Contains protected URLs
    type: stats
    onFail: WARN
    statistic: urlsInContext
    operator: '>='
    value: 30


- type: spiderAjax
  parameters:
    context: flypostContext
    user: flypost-user
    url: http://localhost:3000/
    maxDuration: 20
    maxCrawlDepth: 30
    browserId: firefox-headless
    enableExtensions: true
  tests:
  - name: At least 200 AJAX URLs found
    type: stats
    onFail: INFO
    statistic: spiderAjax.urls.added
    operator: '>='
    value: 200


- type: passiveScan-wait
  parameters: {}

- type: activeScan-config
  parameters:
    defaultPolicy: "Default Policy"
    maxScanDurationInMins: 60
    handleAntiCSRFTokens: true
    threadPerHost: 5

- type: activeScan
  parameters:
    context: flypostContext
    user: flypost-user
  policyDefinition:
    defaultStrength: high
    defaultThreshold: low

- type: report
  parameters:
    theme: original
    reportDir: /home/zap/.ZAP_D/reports/
    reportFile: flypostClub${REPORT}HtmlReport
    template: traditional-html

- type: report
  parameters:
    theme: original
    reportDir: /home/zap/.ZAP_D/reports/
    reportFile: flypostClub${REPORT}JsonReport
    template: traditional-json

- type: exitStatus
  parameters:
    errorLevel: High
    warnLevel: Medium
