env:
  contexts:
  - name: juiceShopContext
    urls:
    - http://localhost:3000/
    includePaths:
    - http://localhost:3000
    - http://localhost:3000/.*
    excludePaths:
    - .*\.js
    - .*\.css
    - .*\.png
    - .*\.jpeg
    authentication:
      method: script
      parameters:
        scriptEngine: "ECMAScript : Graal.js"
        authUrl: http://localhost:3000/rest/user/login
        twoFaUrl: http://localhost:3000/rest/2fa/verify
        script: /home/zap/.ZAP/scripts/authentication/2FA.js
        scriptName: "2FA Auth Script"
        scriptType: "authentication"
        scriptDescription: "2FA Authentication Script"
        # otpauth://totp/OWASP%20Juice%20Shop:test@mail.com?secret=LVNT2ARXHR3XUFLS&issuer=OWASP%20Juice%20Shop
        sharedSecret: LVNT2ARXHR3XUFLS
      verification:
        method: response
        loggedOutRegex: (Unauthorized)|(token expired)
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: script
      parameters:
        scriptEngine: "ECMAScript : Graal.js"
        script: "/home/zap/.ZAP/scripts/session/juice_shop_session.js" 
        scriptName: "juice_shop_session"
        # scriptType: "authentication"
        scriptDescription: "Juice Shop Auth Script"
    users:
    - name: internal-user
      credentials:
        username: test@mail.com
        password: password01
  parameters: {}

jobs:
- type: passiveScan-config
  parameters: {}

- type: openapi
  parameters:
    context: juiceShopContext
    url: http://localhost:3000/api-docs

- type: spider
  parameters:
    context: juiceShopContext
    user: internal-user
    url: http://localhost:3000
    parseDsStore: true
    maxDuration: 10                   # Int: The max time in minutes the spider will be allowed to run for, default: 0 unlimited
    maxDepth: 100                      # Int: The maximum tree depth to explore, default 5
    maxChildren: 50                  # Int: The maximum number of children to add to 
  tests:
  - name: At least 200 URLs found
    type: stats
    onFail: INFO
    statistic: automation.spider.urls.added
    operator: '>='
    value: 200
  - name: No 401 responses
    type: stats
    onFail: WARN
    statistic: responses.401
    operator: '=='
    value: 0
  - name: No 403 responses
    type: stats
    onFail: WARN
    statistic: responses.403
    operator: '=='
    value: 0

- type: spiderAjax
  parameters:
    context: juiceShopContext
    user: internal-user
    url: http://localhost:3000
    maxDuration: 20
  tests:
  - name: At least 200 AJAX URLs found
    type: stats
    onFail: INFO
    statistic: spiderAjax.urls.added
    operator: '>='
    value: 200

- type: passiveScan-wait
  parameters: {}

- type: activeScan-config
  parameters:
    defaultPolicy: "Default Policy"
    maxScanDurationInMins: 80
    handleAntiCSRFTokens: true
    threadPerHost: 10
- type: activeScan
  parameters:
    context: juiceShopContext
    user: internal-user
  policyDefinition:
    defaultStrength: high             # Устанавливаем силу атак на High
    defaultThreshold: low             # Устанавливаем порог срабатывания на Low
    rules:
      - id: 40018                     # SQL Injection
        strength: insane              # Устанавливаем силу атак на Insane для SQL Injection
        threshold: low
      - id: 40012                     # Cross-Site Scripting (XSS)
        strength: high
        threshold: low
      - id: 40014                     # Path Traversal
        strength: high
        threshold: low

- type: report
  parameters:
    theme: original
    reportDir: /home/zap/.ZAP_D/reports/
    reportFile: juiceShopHtmlReport
    reportTitle: ZAP Scanning Report
  risks:
  - info
  - low
  - medium
  - high
  confidences:
  - falsepositive
  - low
  - medium
  - high
  - confirmed
  sections:
  - siteRiskCounts
  - responseBody
  - appendix
  - alertTypes
  - responseHeader
  - alertTypeCounts
  - riskConfidenceCounts
  - alerts
  - aboutThisReport
  - contents
  - requestBody
  - reportDescription
  - reportParameters
  - requestHeader
  - summaries
- type: report
  parameters:
    template: traditional-xml
    reportDir: /home/zap/.ZAP_D/reports/
    reportFile: juiceShopXmlReport
    reportTitle: ZAP Scanning Report
  risks:
  - info
  - low
  - medium
  - high
  confidences:
  - falsepositive
  - low
  - medium
  - high
  - confirmed

- type: report
  parameters:
    theme: original
    reportDir: /home/zap/.ZAP_D/reports/
    reportFile: juiceShopHtmlReport
    template: traditional-html

- type: report
  parameters:
    theme: original
    reportDir: /home/zap/.ZAP_D/reports/
    reportFile: juiceShopJsonReport
    template: traditional-json

- type: exitStatus
  parameters:
    errorLevel: High
    warnLevel: Medium
